CREATE TABLE IF NOT EXISTS messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(20),
  text TEXT NULL,
  audio_path VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS question_text TEXT NULL AFTER role;

ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS text_grammar TEXT NULL AFTER text;
